services:
  - type: web
    name: vite-et-gourmand
    runtime: docker
    dockerfilePath: ./docker/php/Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL_CA
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGO_DB
        sync: false
      - key: GEOCODER_URL
        value: https://data.geopf.fr/geocodage/search
